### ISSUE TITLE
test_state_dict[weight]=torch.cat(weights,0) input error

### ISSUE THREAD

**Issue by PL23K** [PiggyJerry/DC-Net#1]
Inference-S.py
line 106  test_state_dict[weight]=torch.cat(weights,0)

TypeError: expected Tensor as element 0 in argument 0, but got str

**Comment by PL23K** [comment]
replace weigths -> [state_dict[_] for _ in weights] ？

**Comment by PiggyJerry** [comment]
Dear Zhiyong,

Yes you are right, thank you for correcting.

Best wishes,
Jiayi Zhu

ZhiyongYang ***@***.***> 于2023年7月15日周六 22:06写道：
